import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../../../../src/app/globals.css";

import React from 'react'

import DashHeader from '@/app/components/dashHeader'
import HeaderMobile from "@/app/components/header-mobile";
import SideBar from "@/app/components/Sidebar";
import MarginWidthWrapper from "@/app/components/margin-width-wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hospital",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-black ${inter.className}`}>
        <div className="flex">
          <SideBar />
          <main className="flex-1">
            <MarginWidthWrapper>
        <DashHeader />
        <HeaderMobile />
        {children}
        </MarginWidthWrapper>
        </main>
        </div>
        </body>
    </html>
  );
}
