import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "../components/Navbar/NavBar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header style={{backgroundColor: "lightblue", padding:"25px"}}>  <NavBar/></header>
        {children}
        <footer style={{backgroundColor: "lightblue", padding:"100px"}}></footer>
      </body>
    </html>
  );
}
